/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4cmaas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author AB96600
 */
public class Anaform extends javax.swing.JFrame {

    /**
     * Creates new form Anaform
     */ 
    Hesap2 hsp;
    private boolean esyardim,sendikakaydi,sendikaodenek;
    public Anaform() {
        initComponents();
        hsp = new Hesap2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ogrenimDurumuCmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        medeniDurumCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        altiYasAltiCmb = new javax.swing.JComboBox<>();
        altiYasUstuCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sendikaKaydiCmb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sendikaOdenegiCmb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        fazlaMesaiTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bireyselEmeklilikCmb = new javax.swing.JComboBox<>();
        hesaplaBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        esYardimiCMB = new javax.swing.JComboBox<>();
        adsoyadTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tcKimlikNoTxt = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        sgkNoTxt = new javax.swing.JTextField();
        kaydetBtn = new javax.swing.JButton();
        yazdirBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sozlesmeTutariTXT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cocukYardimiTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        esYardimiTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        agiTutariTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sendikaOdenegiTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        maasUnsurMatrahTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        sgkMatrahTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sgkIsciTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sgkIsverenTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ekOdemeTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fazlaMesaiTxtG = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sendikaAidatiTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        bireyselEmeklilikTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        gelirVergisiMatrahTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        gelirVergisiTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        damgaVergisiMatrahTxt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        damgaVergisiTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        kesintilerToplamiTxt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        odemelerToplamiTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        netOdenenTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4C Maaş Hesaplama Motoru");
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Okul Durumu");

        ogrenimDurumuCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İLKÖĞRETİM", "LİSE", "YÜKSEKOKUL" }));

        jLabel2.setText("Medeni Durumu");

        medeniDurumCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BEKAR", "EVLİ EŞİ ÇALIŞMAYAN ÇOCUKSUZ", "EVLİ EŞİ ÇALIŞMAYAN 1 ÇOCUK", "EVLİ EŞİ ÇALIŞMAYAN 2 ÇOCUK", "EVLİ EŞİ ÇALIŞMAYAN 3 ÇOCUK", "EVLİ EŞİ ÇALIŞMAYAN 4 ÇOCUK", "EVLİ EŞİ ÇALIŞMAYAN 5 ÇOCUK", "EVLİ EŞİ ÇALIŞAN ÇOCUKSUZ", "EVLİ EŞİ ÇALIŞAN 1 ÇOCUKLU", "EVLİ EŞİ ÇALIŞAN 2 ÇOCUKLU", "EVLİ EŞİ ÇALIŞAN 3 ÇOCUKLU", "EVLİ EŞİ ÇALIŞAN 4 ÇOCUKLU", "EVLİ EŞİ ÇALIŞAN 5 ÇOCUKLU" }));
        medeniDurumCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medeniDurumCmbActionPerformed(evt);
            }
        });

        jLabel3.setText("6 Yaşından Küçük Çocuk Sayısı");

        altiYasAltiCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        altiYasUstuCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel4.setText("6 Yaşından Büyük Çocuk Sayısı");

        jLabel5.setText("Sendikaya Kayıtlı mı ?");

        sendikaKaydiCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAYITLI", "KAYITLI DEĞİL" }));

        jLabel6.setText("Bu ay Sendika Ödeneği Var mı ?");
        jLabel6.setToolTipText("");

        sendikaOdenegiCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YOK", "VAR" }));

        jLabel7.setText("Fazla Mesai Ücreti");
        jLabel7.setToolTipText("");

        jLabel8.setText("Zorunlu Bireysel Emeklilik");
        jLabel8.setToolTipText("");

        bireyselEmeklilikCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YOK", "VAR" }));

        hesaplaBtn.setText("Hesapla");
        hesaplaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Eş Yardımı");

        esYardimiCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALIYOR", "ALMIYOR" }));

        adsoyadTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adsoyadTxtMouseClicked(evt);
            }
        });

        jLabel30.setText("Adı Soyadı");
        jLabel30.setToolTipText("");

        jLabel31.setText("TC Kimlik No");
        jLabel31.setToolTipText("");

        jLabel32.setText("SGK No");
        jLabel32.setToolTipText("");

        kaydetBtn.setText("Kaydet");
        kaydetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetBtnActionPerformed(evt);
            }
        });

        yazdirBtn.setText("Yazdır()");
        yazdirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazdirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(esYardimiCMB, 0, 323, Short.MAX_VALUE)
                            .addComponent(altiYasUstuCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(altiYasAltiCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sgkNoTxt)
                            .addComponent(tcKimlikNoTxt)
                            .addComponent(adsoyadTxt)
                            .addComponent(ogrenimDurumuCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medeniDurumCmb, 0, 323, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bireyselEmeklilikCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendikaOdenegiCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendikaKaydiCmb, 0, 323, Short.MAX_VALUE)
                            .addComponent(fazlaMesaiTxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kaydetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hesaplaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(yazdirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(adsoyadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tcKimlikNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(sgkNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ogrenimDurumuCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(medeniDurumCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(altiYasAltiCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(altiYasUstuCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(esYardimiCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sendikaKaydiCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sendikaOdenegiCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fazlaMesaiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bireyselEmeklilikCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hesaplaBtn)
                    .addComponent(kaydetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yazdirBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Sözleşme Tutarı ");

        sozlesmeTutariTXT.setEditable(false);
        sozlesmeTutariTXT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("Çocuk Yardımı");

        cocukYardimiTxt.setEditable(false);
        cocukYardimiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("Eş Yardımı");

        esYardimiTxt.setEditable(false);
        esYardimiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("AGI Tutarı");

        agiTutariTxt.setEditable(false);
        agiTutariTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Sendika Ödeneği");

        sendikaOdenegiTxt.setEditable(false);
        sendikaOdenegiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setText("Maaş Unsur Matrah");

        maasUnsurMatrahTxt.setEditable(false);
        maasUnsurMatrahTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setText("SGK Matrahı");

        sgkMatrahTxt.setEditable(false);
        sgkMatrahTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setText("SGK İşçi %14");

        sgkIsciTxt.setEditable(false);
        sgkIsciTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel18.setText("SGK İşveren %20.5");

        sgkIsverenTxt.setEditable(false);
        sgkIsverenTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel19.setText("Ek Ödeme");

        ekOdemeTxt.setEditable(false);
        ekOdemeTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setText("Fazla Mesai");

        fazlaMesaiTxtG.setEditable(false);
        fazlaMesaiTxtG.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel21.setText("Sendika Aidatı");

        sendikaAidatiTxt.setEditable(false);
        sendikaAidatiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel22.setText("Bireysel Emeklilik");

        bireyselEmeklilikTxt.setEditable(false);
        bireyselEmeklilikTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel23.setText("Gelir Vergisi Matrah");

        gelirVergisiMatrahTxt.setEditable(false);
        gelirVergisiMatrahTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel24.setText("Gelir Vergisi");

        gelirVergisiTxt.setEditable(false);
        gelirVergisiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel25.setText("Damga Vergisi Matrah");

        damgaVergisiMatrahTxt.setEditable(false);
        damgaVergisiMatrahTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel26.setText("Damga Vergisi");

        damgaVergisiTxt.setEditable(false);
        damgaVergisiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel27.setText("Kesintiler Toplamı");

        kesintilerToplamiTxt.setEditable(false);
        kesintilerToplamiTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kesintilerToplamiTxt.setForeground(new java.awt.Color(255, 0, 0));
        kesintilerToplamiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        kesintilerToplamiTxt.setCaretColor(new java.awt.Color(255, 0, 0));

        jLabel28.setText("Ödemeler Toplamı");

        odemelerToplamiTxt.setEditable(false);
        odemelerToplamiTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        odemelerToplamiTxt.setForeground(new java.awt.Color(51, 204, 0));
        odemelerToplamiTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel29.setText("NET ÖDENEN");

        netOdenenTxt.setEditable(false);
        netOdenenTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netOdenenTxt.setForeground(new java.awt.Color(51, 204, 0));
        netOdenenTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sozlesmeTutariTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cocukYardimiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(esYardimiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agiTutariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendikaOdenegiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maasUnsurMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sgkMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sgkIsciTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sgkIsverenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ekOdemeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fazlaMesaiTxtG, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendikaAidatiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bireyselEmeklilikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gelirVergisiMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gelirVergisiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(damgaVergisiMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(damgaVergisiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kesintilerToplamiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odemelerToplamiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(netOdenenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(sozlesmeTutariTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sendikaAidatiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bireyselEmeklilikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cocukYardimiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gelirVergisiMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(esYardimiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gelirVergisiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(agiTutariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(damgaVergisiMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(sendikaOdenegiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(damgaVergisiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(maasUnsurMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kesintilerToplamiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(sgkMatrahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(odemelerToplamiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(sgkIsciTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(netOdenenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(sgkIsverenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ekOdemeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(fazlaMesaiTxtG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medeniDurumCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medeniDurumCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medeniDurumCmbActionPerformed

    private void hesaplaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaBtnActionPerformed
        DecimalFormat df = new DecimalFormat("#.##");
        // SETLEMELER
        
        
        hsp.setOkulGosterge(ogrenimDurumuCmb.getSelectedIndex()+1);
        
        
        hsp.setAltiYasBuyuk(Integer.parseInt((String) altiYasUstuCmb.getSelectedItem()));
        hsp.setAltiYasKucuk(Integer.parseInt((String) altiYasAltiCmb.getSelectedItem()));
        if (esYardimiCMB.getSelectedItem()=="ALIYOR") {
            hsp.setEsYardimi(true);
        } else hsp.setEsYardimi(false);
        if (esYardimiCMB.getSelectedItem()=="ALIYOR") {
            hsp.setEsIstisna(true);
        } else hsp.setEsIstisna(false);
        
        if (sendikaKaydiCmb.getSelectedItem()=="KAYITLI") {
            hsp.setSendikaAidati(true);
        } else hsp.setSendikaAidati(false);

        
        hsp.setAgiMiktari(medeniDurumCmb.getSelectedIndex());
     
        
        
        if (sendikaOdenegiCmb.getSelectedItem()=="VAR") {
            hsp.setSendikaOdenegi(false);
        } else hsp.setSendikaOdenegi(true);
        
        if(fazlaMesaiTxt.getText().isEmpty()) {
            fazlaMesaiTxt.setText("0");
        }
        
        hsp.setFazlaMesai(Double.parseDouble(fazlaMesaiTxt.getText()));
        
        
        if (bireyselEmeklilikCmb.getSelectedItem()=="VAR") {
            hsp.setBireyselEmeklilik(false);        
        } else hsp.setBireyselEmeklilik(true);

        hsp.setGelirVergisi(15);
        
        //SETLEMELER SONU
        
        sozlesmeTutariTXT.setText(String.valueOf(df.format(hsp.getSozlesmeUcreti())));
        cocukYardimiTxt.setText(String.valueOf(df.format(hsp.getCocukYardimi())));
        esYardimiTxt.setText(String.valueOf(df.format(hsp.getEsYardimi())));
        agiTutariTxt.setText(String.valueOf(df.format(hsp.getAgiMiktari())));
        sendikaOdenegiTxt.setText(String.valueOf(df.format(hsp.getSendikaOdenegi())));
        maasUnsurMatrahTxt.setText(String.valueOf(df.format(hsp.getMaasMatrahi())));
        sgkMatrahTxt.setText(String.valueOf(df.format(hsp.getSgkMatrahi())));
        sgkIsciTxt.setText(String.valueOf(df.format(hsp.getSgkIsci())));
        sgkIsverenTxt.setText(String.valueOf(df.format(hsp.getSgkIsveren())));
        ekOdemeTxt.setText(String.valueOf(df.format(hsp.getEkOdeme())));
        fazlaMesaiTxtG.setText(String.valueOf(df.format(hsp.getFazlaMesai())));
        sendikaAidatiTxt.setText(String.valueOf(df.format(hsp.getSendikaAidati())));
        bireyselEmeklilikTxt.setText(String.valueOf(df.format(hsp.getBireyselEmeklilik())));
        gelirVergisiMatrahTxt.setText(String.valueOf(df.format(hsp.getGelirVergisiMatrahi())));
        gelirVergisiTxt.setText(String.valueOf(df.format(hsp.getGelirVergisi())));
        damgaVergisiMatrahTxt.setText(String.valueOf(df.format(hsp.getDamgaVergisiMatrahi())));
        damgaVergisiTxt.setText(String.valueOf(df.format(hsp.getDamgaVergisi())));
        kesintilerToplamiTxt.setText(String.valueOf(df.format(hsp.getKesintilerToplami())));
        odemelerToplamiTxt.setText(String.valueOf(df.format(hsp.getOdemelerToplami())));       
        netOdenenTxt.setText(String.valueOf(df.format(hsp.getNetOdenen())));

        
        
        
        
        
    }//GEN-LAST:event_hesaplaBtnActionPerformed

    private void kaydetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetBtnActionPerformed
        try {
            if (adsoyadTxt.getText().isEmpty()==false) 
            {           
            Class.forName("com.mysql.jdbc.Driver");
            Connection baglanti = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/dortcmaas?useUnicode=true&characterEncoding=UTF-8","efe","sallama");            
            
            String kaydet = "insert into kisiler (adsoyad, tckimlikno, sgkno, ogrenimdurumu, medenidurumu, altiyaskucuk, altiyasbuyuk, esyardimi, sendikakaydi, sendikaodenegi, fazlamesai, zorunlubireysel) values ('"+adsoyadTxt.getText().toString().trim()+"','"+tcKimlikNoTxt.getText().toString().trim()+"','"+sgkNoTxt.getText().toString().trim()+"','"+ogrenimDurumuCmb.getSelectedItem()+"','"+medeniDurumCmb.getSelectedItem()+"','"+altiYasAltiCmb.getSelectedItem()+"','"+altiYasUstuCmb.getSelectedItem()+"','"+esYardimiCMB.getSelectedItem()+"','"+sendikaKaydiCmb.getSelectedItem()+"','"+sendikaOdenegiCmb.getSelectedItem()+"','"+fazlaMesaiTxt.getText().toString().trim()+"','"+bireyselEmeklilikCmb.getSelectedItem()+"')";
            Statement stm = (Statement) baglanti.createStatement();
            
            int sonuc = stm.executeUpdate(kaydet);
            System.out.println(sonuc);
            
            baglanti.close();
            } else {
                JOptionPane.showMessageDialog(rootPane, "İsim alanı boş olamaz!");
                adsoyadTxt.setBackground(Color.red);
                adsoyadTxt.setForeground(Color.white);
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("sınıf bulunamadı");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_kaydetBtnActionPerformed

    private void yazdirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yazdirBtnActionPerformed
        
    }//GEN-LAST:event_yazdirBtnActionPerformed

    private void adsoyadTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adsoyadTxtMouseClicked
        adsoyadTxt.setBackground(Color.white);
        adsoyadTxt.setForeground(Color.BLACK);
    }//GEN-LAST:event_adsoyadTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anaform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adsoyadTxt;
    private javax.swing.JTextField agiTutariTxt;
    private javax.swing.JComboBox<String> altiYasAltiCmb;
    private javax.swing.JComboBox<String> altiYasUstuCmb;
    private javax.swing.JComboBox<String> bireyselEmeklilikCmb;
    private javax.swing.JTextField bireyselEmeklilikTxt;
    private javax.swing.JTextField cocukYardimiTxt;
    private javax.swing.JTextField damgaVergisiMatrahTxt;
    private javax.swing.JTextField damgaVergisiTxt;
    private javax.swing.JTextField ekOdemeTxt;
    private javax.swing.JComboBox<String> esYardimiCMB;
    private javax.swing.JTextField esYardimiTxt;
    private javax.swing.JTextField fazlaMesaiTxt;
    private javax.swing.JTextField fazlaMesaiTxtG;
    private javax.swing.JTextField gelirVergisiMatrahTxt;
    private javax.swing.JTextField gelirVergisiTxt;
    private javax.swing.JButton hesaplaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kaydetBtn;
    private javax.swing.JTextField kesintilerToplamiTxt;
    private javax.swing.JTextField maasUnsurMatrahTxt;
    private javax.swing.JComboBox<String> medeniDurumCmb;
    private javax.swing.JTextField netOdenenTxt;
    private javax.swing.JTextField odemelerToplamiTxt;
    private javax.swing.JComboBox<String> ogrenimDurumuCmb;
    private javax.swing.JTextField sendikaAidatiTxt;
    private javax.swing.JComboBox<String> sendikaKaydiCmb;
    private javax.swing.JComboBox<String> sendikaOdenegiCmb;
    private javax.swing.JTextField sendikaOdenegiTxt;
    private javax.swing.JTextField sgkIsciTxt;
    private javax.swing.JTextField sgkIsverenTxt;
    private javax.swing.JTextField sgkMatrahTxt;
    private javax.swing.JTextField sgkNoTxt;
    private javax.swing.JTextField sozlesmeTutariTXT;
    private javax.swing.JTextField tcKimlikNoTxt;
    private javax.swing.JButton yazdirBtn;
    // End of variables declaration//GEN-END:variables
}
